// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: translit/translit.proto

package translit

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Word struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *Word) Reset() {
	*x = Word{}
	if protoimpl.UnsafeEnabled {
		mi := &file_translit_translit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Word) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Word) ProtoMessage() {}

func (x *Word) ProtoReflect() protoreflect.Message {
	mi := &file_translit_translit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Word.ProtoReflect.Descriptor instead.
func (*Word) Descriptor() ([]byte, []int) {
	return file_translit_translit_proto_rawDescGZIP(), []int{0}
}

func (x *Word) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

var File_translit_translit_proto protoreflect.FileDescriptor

var file_translit_translit_proto_rawDesc = []byte{
	0x0a, 0x17, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x69, 0x74, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x6c, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x6c, 0x69, 0x74, 0x22, 0x1a, 0x0a, 0x04, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x32,
	0x36, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x69, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x45,
	0x6e, 0x52, 0x75, 0x12, 0x0e, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x69, 0x74, 0x2e, 0x57,
	0x6f, 0x72, 0x64, 0x1a, 0x0e, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x69, 0x74, 0x2e, 0x57,
	0x6f, 0x72, 0x64, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x6c, 0x69, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_translit_translit_proto_rawDescOnce sync.Once
	file_translit_translit_proto_rawDescData = file_translit_translit_proto_rawDesc
)

func file_translit_translit_proto_rawDescGZIP() []byte {
	file_translit_translit_proto_rawDescOnce.Do(func() {
		file_translit_translit_proto_rawDescData = protoimpl.X.CompressGZIP(file_translit_translit_proto_rawDescData)
	})
	return file_translit_translit_proto_rawDescData
}

var file_translit_translit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_translit_translit_proto_goTypes = []interface{}{
	(*Word)(nil), // 0: translit.Word
}
var file_translit_translit_proto_depIdxs = []int32{
	0, // 0: translit.Translit.EnRu:input_type -> translit.Word
	0, // 1: translit.Translit.EnRu:output_type -> translit.Word
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_translit_translit_proto_init() }
func file_translit_translit_proto_init() {
	if File_translit_translit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_translit_translit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Word); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_translit_translit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_translit_translit_proto_goTypes,
		DependencyIndexes: file_translit_translit_proto_depIdxs,
		MessageInfos:      file_translit_translit_proto_msgTypes,
	}.Build()
	File_translit_translit_proto = out.File
	file_translit_translit_proto_rawDesc = nil
	file_translit_translit_proto_goTypes = nil
	file_translit_translit_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TranslitClient is the client API for Translit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TranslitClient interface {
	EnRu(ctx context.Context, opts ...grpc.CallOption) (Translit_EnRuClient, error)
}

type translitClient struct {
	cc grpc.ClientConnInterface
}

func NewTranslitClient(cc grpc.ClientConnInterface) TranslitClient {
	return &translitClient{cc}
}

func (c *translitClient) EnRu(ctx context.Context, opts ...grpc.CallOption) (Translit_EnRuClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Translit_serviceDesc.Streams[0], "/translit.Translit/EnRu", opts...)
	if err != nil {
		return nil, err
	}
	x := &translitEnRuClient{stream}
	return x, nil
}

type Translit_EnRuClient interface {
	Send(*Word) error
	Recv() (*Word, error)
	grpc.ClientStream
}

type translitEnRuClient struct {
	grpc.ClientStream
}

func (x *translitEnRuClient) Send(m *Word) error {
	return x.ClientStream.SendMsg(m)
}

func (x *translitEnRuClient) Recv() (*Word, error) {
	m := new(Word)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TranslitServer is the server API for Translit service.
type TranslitServer interface {
	EnRu(Translit_EnRuServer) error
}

// UnimplementedTranslitServer can be embedded to have forward compatible implementations.
type UnimplementedTranslitServer struct {
}

func (*UnimplementedTranslitServer) EnRu(Translit_EnRuServer) error {
	return status.Errorf(codes.Unimplemented, "method EnRu not implemented")
}

func RegisterTranslitServer(s *grpc.Server, srv TranslitServer) {
	s.RegisterService(&_Translit_serviceDesc, srv)
}

func _Translit_EnRu_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TranslitServer).EnRu(&translitEnRuServer{stream})
}

type Translit_EnRuServer interface {
	Send(*Word) error
	Recv() (*Word, error)
	grpc.ServerStream
}

type translitEnRuServer struct {
	grpc.ServerStream
}

func (x *translitEnRuServer) Send(m *Word) error {
	return x.ServerStream.SendMsg(m)
}

func (x *translitEnRuServer) Recv() (*Word, error) {
	m := new(Word)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Translit_serviceDesc = grpc.ServiceDesc{
	ServiceName: "translit.Translit",
	HandlerType: (*TranslitServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EnRu",
			Handler:       _Translit_EnRu_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "translit/translit.proto",
}
